### PR TITLE
mkrofs: Workaround GCC 15.2 issue with sanitizers

### LINKED ISSUE #1477: mkrofs: fail to build with gcc 15.2.0
# Description
ENV: Ubuntu 25.10, gcc (Ubuntu 15.2.0-4ubuntu4) 15.2.0

`TARGET=host-generic-pc ./phoenix-rtos-build/build.sh clean all`

ends with following error:

```
In function ‘basestrncpy’,
    inlined from ‘processDir’ at /home/anglov/Project/code/phoenix-rtos-project/phoenix-rtos-hostutils/mkrofs/mkrofs.c:283:2:
/home/anglov/Project/code/phoenix-rtos-project/phoenix-rtos-hostutils/mkrofs/mkrofs.c:30:23: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
   30 | #define LOG_prefix    "rofs: "
      |                       ^~~~~~~~
/home/anglov/Project/code/phoenix-rtos-project/phoenix-rtos-hostutils/mkrofs/mkrofs.c:32:39: note: in expansion of macro ‘LOG_prefix’
   32 | #define ERR(fmt, ...) fprintf(stderr, LOG_prefix fmt "\n", ##__VA_ARGS__)
      |                                       ^~~~~~~~~~
/home/anglov/Project/code/phoenix-rtos-project/phoenix-rtos-hostutils/mkrofs/mkrofs.c:225:17: note: in expansion of macro ‘ERR’
  225 |                 ERR("Name '%s' will be trimmed to %zu characters", tmp, len);
      |                 ^~~
```

# Analysis

This issue is not reproducible during normal target build. It's due to fact, that sanitizers is not enabled then.

After looking at the compilation options it seems, that issue only occurs while:
- sanitizers are enabled
- optimization level is -O2 or higher (-Os and -Og doesn't trigger the issue)

Looking at documentation and glibc code, basename should always return non-null. So this code should have never null on %s format (tmp should never be null):
https://github.com/phoenix-rtos/phoenix-rtos-hostutils/blob/b7314da92486dd192dca228c25f8fc5cb5ce718f/mkrofs/mkrofs.c#L221
```c
(...)
	tmp = basename(strcpy((char *)common.buf, src));

	size_t tmplen = strlen(tmp);
	if (tmplen >= len) {
		ERR("Name '%s' will be trimmed to %zu characters", tmp, len);
		memcpy(dst, tmp, len);
	}
(...)
```
So I assume, that this error is gcc false-positive somehow connected with sanitizers and optimization.

# Possible sollution
I open that issue instead of making a PR mainly because not sure what is better.

I checked that explicit check on `tmp == NULL` will silent the error. But in theory this check is redundant, and not-null should be asserted by stdlib.

Another solution I see is to disable warning by the pragma. 

I have mixed feeling to both solution (first create redundancy, second involves compiler-dependent pragmas). I leave this issue to open discussion how we should workaround compiler false-positives, also in less critical code as we have here.

### PR DESCRIPTION
**Pull request by anglov**
Due to compiler false-positive, build not working with enabled sanitizers and optimization level >= -O2. To workaround this, explicit check is required.

## Description

Description in linked issue
FIXES: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1477

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (refactoring, style fixes, git/CI config, submodule management, no code logic changes)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: build&test on host-generic-pc

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

File: mkrofs/mkrofs.c [hunk 1]
```diff
@@ -219,7 +219,15 @@ static void basestrncpy(char *dst, const char *src, size_t len)
...
 	}
 	tmp = basename(strcpy((char *)common.buf, src));
-
+	/*
+	 * NOTE: According to basename documentation and implementation, should never happen. Required due to GCC 15.2
+	 * See: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1477
+	 * */
+	if (tmp == NULL) {
+		assert(false);
+		ERR("unexpected error");
```
Comment (adamgreloch) [inline mkrofs/mkrofs.c:227]: wouldn't `assert(tmp != NULL)` suffice?

Comment (nalajcie) [reply mkrofs/mkrofs.c:227]: no, in `NDEBUG` build there is no assert. You need to call function with attribute `noreturn` inside `if`  :/

Probably in our header we could attribute the function as `returns_nonnull`, but glibc lacks this attribute (at least on Ubuntu 25.10), so we need to guard against it in our code - for the tool to be compilable on host.

alternative is to silence the error for the false-positive lines with Pragma

Comment (adamgreloch) [reply mkrofs/mkrofs.c:227]: Yeah, I see. What about:
```
if (tmp == NULL) {
__builtin_unreachable();
}
```
The GCC will then optimize the whole path away

Comment (adamgreloch) [reply mkrofs/mkrofs.c:227]: OTOH maybe it's better to keep explicit runtime handling even in obviously false cases. The `unreachable` "trick" will introduce UB if the condition happens to be true and I don't think it's a good idea to promote such ideas in the codebase

Comment (anglov) [reply mkrofs/mkrofs.c:227]: I am open to all options, just want to have working build.

TBH I didn't care for pureness in terms of code performance in case of obvious compiler mistakes on host util, which is run in build time (no code that will come on low-resources hardware).

I don't like pragmas, due to it compiler dependency but I am ok to use it, if we say that we want to handle that  cases in our codebase that way.

I decided on explicit check at the first take as it's 100% compatible with all compilers and it's impact on performance should be marginal enough to do not care about it.

Comment (adamgreloch) [reply mkrofs/mkrofs.c:227]: For me the proposed change is fine, except for the `assert(false)` - not sure it's needed when we do `exit(1)` anyways

Comment (anglov) [reply mkrofs/mkrofs.c:227]: For me it's semantic – shows path that should be unreachable, and inform developer that something goes really wrong. But ofc, I can remove it if you want to :)

Comment (adamgreloch) [reply mkrofs/mkrofs.c:227]: Up to you, IMO the comment + `ERR` wording sufficiently emphasizes the path's unreachability

Comment (anglov) [reply mkrofs/mkrofs.c:227]: Done

**Review by adamgreloch — APPROVED** [review]
